# Generated by Django 6.0.4 on 2026-05-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaClasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'competencia_clasificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'puesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('id_clasificacion', models.ForeignKey(db_column='id_clasificacion', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.competenciaclasificacion')),
            ],
            options={
                'db_table': 'competencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_largo', models.CharField(max_length=255)),
                ('es_jefe_departamento', models.BooleanField(default=False, verbose_name='¿Es la cabeza de este departamento?')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.departamento')),
                ('id_jefe', models.ForeignKey(blank=True, db_column='id_jefe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empleado', verbose_name='Jefe Inmediato')),
                ('id_puesto', models.ForeignKey(db_column='id_puesto', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.puesto')),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDet',
            fields=[
                ('pk', models.CompositePrimaryKey('id_evaluacion', 'id_competencia', 'id_empleado', 'tipo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=1)),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.competencia')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.empleado')),
                ('id_evaluacion', models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.evaluacion')),
            ],
            options={
                'db_table': 'evaluacion_det',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='competenciaclasificacion',
            name='id_puesto',
            field=models.ForeignKey(blank=True, db_column='id_puesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rh.puesto'),
        ),
    ]
