# Generated by Django 6.0.4 on 2026-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado_empleado',
            field=models.CharField(default='A', max_length=1, verbose_name='Estado (A=Activo, B=Baja)'),
        ),
    ]
