# Generated by Django 6.0.4 on 2026-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_empleado_estado_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado_empleado',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], default='A', max_length=1, verbose_name='Estado del Empleado'),
        ),
    ]
