# Generated by Django 6.0.4 on 2026-05-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_empleado_estado_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenciaclasificacion',
            options={'managed': True, 'verbose_name': 'Competencia clasificación', 'verbose_name_plural': 'Competencia Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'managed': True, 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
    ]
