# Generated by Django 6.0.4 on 2026-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_competenciaclasificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaclasificacion',
            name='tipo',
            field=models.CharField(choices=[('G', 'General'), ('E', 'Específica')], default='G', max_length=1, verbose_name='Tipo Competencia'),
        ),
    ]
