# Generated by Django 6.0.4 on 2026-05-20 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_competenciaclasificacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'managed': True, 'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterField(
            model_name='competencia',
            name='id_clasificacion',
            field=models.ForeignKey(db_column='id_clasificacion', on_delete=django.db.models.deletion.DO_NOTHING, to='rh.competenciaclasificacion', verbose_name='Clasificación'),
        ),
    ]
