# Generated by Django 6.0.4 on 2026-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondet',
            name='tipo',
            field=models.CharField(choices=[('E', 'Empleado (Autoevaluación)'), ('J', 'Jefe (Evaluación a Colaborador)')], max_length=1),
        ),
    ]
