# Generated by Django 6.0.4 on 2026-05-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_alter_evaluaciondet_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloque', models.CharField(choices=[('G', 'Generales'), ('E', 'Específicas')], max_length=1)),
                ('tipo_evaluador', models.CharField(choices=[('E', 'Empleado (Autoevaluación)'), ('J', 'Jefe (Evaluación a Colaborador)')], max_length=1)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('areas_oportunidad', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleado')),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.evaluacion')),
            ],
            options={
                'unique_together': {('id_evaluacion', 'id_empleado', 'tipo_bloque', 'tipo_evaluador')},
            },
        ),
    ]
