# Generated by Django 6.0.4 on 2026-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_evaluacioncomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='cerrada',
            field=models.BooleanField(default=False, verbose_name='¿Evaluación Cerrada?'),
        ),
    ]
