# Generated by Django 6.0.4 on 2026-05-26 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_evaluacion_cerrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenciaclasificacion',
            name='id_puesto',
        ),
        migrations.CreateModel(
            name='ClasificacionPorEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Proyecto especial 2026', max_length=255, null=True)),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.competenciaclasificacion', verbose_name='Clasificación Extra')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Clasificación Especial por Empleado',
                'verbose_name_plural': 'Excepciones: Clasificaciones por Empleado',
                'unique_together': {('id_empleado', 'id_clasificacion')},
            },
        ),
        migrations.CreateModel(
            name='ClasificacionPorPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.competenciaclasificacion', verbose_name='Clasificación Asignada')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Clasificación por Puesto',
                'verbose_name_plural': 'Matriz: Clasificaciones por Puesto',
                'unique_together': {('id_puesto', 'id_clasificacion')},
            },
        ),
    ]
