# Generated by Django 6.0.4 on 2026-05-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_remove_competenciaclasificacion_id_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionporempleado',
            name='competencia_exclusiva',
            field=models.ForeignKey(blank=True, help_text='Si seleccionas una competencia aquí, al empleado SOLO se le evaluará esta competencia de la clasificación. Si lo dejas vacío, se le evaluarán todas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.competencia'),
        ),
    ]
