# Generated by Django 6.0.4 on 2026-05-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_clasificacionporempleado_competencia_exclusiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionporempleado',
            name='competencia_exclusiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.competencia', verbose_name='ID Competencia Exclusiva'),
        ),
        migrations.CreateModel(
            name='EmpleadoCompetenciaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.competencia')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_asignadas', to='rh.empleado')),
            ],
            options={
                'verbose_name': 'Competencias Asignadas',
                'unique_together': {('id_empleado', 'id_competencia')},
            },
        ),
    ]
