# Generated by Django 6.0.4 on 2026-06-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_alter_clasificacionporempleado_competencia_exclusiva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'ordering': ['nombre_largo'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
