# Generated by Django 6.0.4 on 2026-06-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
    ]
