# Generated by Django 6.0.4 on 2026-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaclasificacion',
            name='tipo',
            field=models.CharField(choices=[('G', 'General'), ('E', 'Específica')], default='E', max_length=1, verbose_name='Tipo Competencia'),
        ),
    ]
