# Generated by Django 6.0.4 on 2026-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_alter_competenciaclasificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechaalta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
    ]
