# Generated by Django 6.0.4 on 2026-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_empleado_fechaalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='CorreoElectronico',
            field=models.CharField(default='', max_length=60, verbose_name='Correo'),
        ),
    ]
