# Generated by Django 6.0.4 on 2026-06-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_empleado_correoelectronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='CorreoElectronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
