# Generated by Django 6.0.4 on 2026-06-30 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_alter_empleado_correoelectronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAccesoEvaluacion',
            fields=[
                ('id_token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empleado')),
            ],
        ),
    ]
