# Generated by Django 6.0.4 on 2026-07-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_tokenaccesoevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='se_evalua',
            field=models.BooleanField(default=False, verbose_name='¿Se evalúa?'),
        ),
    ]
