# Generated by Django 6.0.4 on 2026-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_empleado_se_evalua'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadocompetenciaasignada',
            options={'verbose_name': 'Competencia Asignada a Empleado', 'verbose_name_plural': 'Competencias Asignadas'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='es_jefe_departamento',
            field=models.BooleanField(default=False, verbose_name='Encargado'),
        ),
        migrations.AlterModelTable(
            name='clasificacionporempleado',
            table='rh_clasificacionporempleado',
        ),
        migrations.AlterModelTable(
            name='clasificacionporpuesto',
            table='rh_clasificacionporpuesto',
        ),
        migrations.AlterModelTable(
            name='competencia',
            table='rh_competencia',
        ),
        migrations.AlterModelTable(
            name='competenciaclasificacion',
            table='rh_competencia_clasificacion',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='rh_departamento',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='rh_empleado',
        ),
        migrations.AlterModelTable(
            name='empleadocompetenciaasignada',
            table='rh_empleadocompetenciaasignada',
        ),
        migrations.AlterModelTable(
            name='evaluacion',
            table='rh_evaluacion',
        ),
        migrations.AlterModelTable(
            name='evaluacioncomentario',
            table='rh_evaluacioncomentario',
        ),
        migrations.AlterModelTable(
            name='evaluaciondet',
            table='rh_evaluacion_det',
        ),
        migrations.AlterModelTable(
            name='puesto',
            table='rh_puesto',
        ),
        migrations.AlterModelTable(
            name='tokenaccesoevaluacion',
            table='rh_tokenaccesoevaluacion',
        ),
    ]
