"""
Django settings for sistema_evaluacion project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!(f%q0r1-&0&mhlf@x+qx!u#vz^gv+y3iofdyx#d7-b-@)8s-w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',  # Primero la estructura base de Unfold
    'unfold.contrib.filters',
    
    'django.contrib.admin',  # Luego el bloque nativo de Django
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rh.apps.RhConfig',  # <-- MUEVE TU APP AQUÍ AL FINAL DEL BLOQUE
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # ⬇️ AGREGA ESTA LÍNEA EXACTA AQUÍ ⬇️
    'django.middleware.locale.LocaleMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'sistema_evaluacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'rh' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # ⬇️ AGREGA ESTA LÍNEA EXACTA AQUÍ ⬇️
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_evaluacion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', # El nombre por defecto en Supabase
        'USER': 'postgres.jodxrpuucmwerqdfytro', # El usuario por defecto
        'PASSWORD': 'Frutas_123@', # La contraseña que guardaste en el Paso 1
        'HOST': 'aws-1-us-west-1.pooler.supabase.com', # Reemplaza con tu Host de Supabase
        'PORT': '6543', 
        'OPTIONS': {
            'options': '-c search_path=public'  # <-- Agrega esta línea exacta
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# =========================================================================
# CONFIGURACIÓN DE IDIOMA Y REGIÓN (CORREGIDO MÈXICO)
# =========================================================================

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True
USE_TZ = True

# Desactivamos la localización automática regional para obligar a usar
# nuestras reglas manuales estrictas de separadores.
USE_L10N = False

DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# =========================================================================
# CONFIGURACIÓN UNIFICADA DE DJANGO UNFOLD
# =========================================================================
# =========================================================================
# CONFIGURACIÓN UNIFICADA DE DJANGO UNFOLD CORREGIDA
# =========================================================================
UNFOLD = {
    "SITE_TITLE": "Recursos Humanos",
    "SITE_HEADER": "Recursos Humanos",

    "SIDEBAR_CHANGED": False,  # Evita que el JS de Unfold colapse el menú por el ancho de tus tablas
    
    "COLORS": {
        "primary": {
            "50": "#f4f9f1",   
            "100": "#e6f3df",
            "200": "#cfe7c2",
            "300": "#b1d79c",  
            "400": "#93c375",
            "500": "#72a651",  # Verde Pistache Central
            "600": "#5b893f",  
            "700": "#476b32",  
            "800": "#3a562b",
            "900": "#314925",
            "950": "#1a2912",
        },
    },
    
    # MENÚ LATERAL PROPIO DE UNFOLD
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Evaluaciones de Desempeño",
                "separator": True,
                "items": [
                    {
                        "title": "Mi Panel de Evaluación",
                        "link": "/admin/panel-evaluacion/", 
                        "icon": "badge",
                    },
                    {
                        "title": "Consolidado Resultados",
                        "link": "/admin/resumen-evaluaciones/", 
                        "icon": "analytics",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ]
            },
            {
                "title": "Catálogos del Sistema",
                "separator": True,
                "items": [
                    {
                        "title": "Empleados",
                        "link": "/admin/rh/empleado/",
                        "icon": "people",
                    },
                    {
                        "title": "Puestos",
                        "link": "/admin/rh/puesto/",
                        "icon": "work",
                    },
                    {
                        "title": "Departamentos",
                        "link": "/admin/rh/departamento/",
                        "icon": "domain",
                    },
                    {
                        "title": "Competencias",
                        "link": "/admin/rh/competencia/",
                        "icon": "star",
                    },
                    {
                        "title": "Clasificación de Competencias",
                        "link": "/admin/rh/competenciaclasificacion/",
                        "icon": "layers",
                    },
                    {
                        "title": "Configurar Evaluaciones",
                        "icon": "event_note",
                        "link": "/admin/rh/evaluacion/", 
                    },                    
                ],
            },
        ],
    },


    # INYECCIÓN ADAPTATIVA DIRECTA AL DOM (Incluye parches mecánicos para proteger el Sidebar)
    "SCRIPTS": [
        lambda request: """
        <script>
            (function() {
                var css = `
                    /* --- 1. FIJAR SIDEBAR ANTE DESBORDAMIENTOS --- */
                    #sidebar, .unfold-sidebar, [data-sidebar], .sidebar-content {
                        display: block !important;
                        visibility: visible !important;
                        opacity: 1 !important;
                        transform: none !important;
                    }

                    /* --- 2. MENÚ LATERAL: TEXTOS, HOVERS Y ACTIVOS --- */
                    [class*="text-primary-"], [class*="text-purple-"], [class*="text-indigo-"],
                    .sidebar-item-active, [aria-current="page"] {
                        color: #5b893f !important;
                    }
                    
                    [class*="bg-primary-600"], [class*="bg-purple-600"], [class*="bg-indigo-600"] {
                        background-color: #72a651 !important;
                        color: #ffffff !important;
                    }
                    
                    a[href*="/admin/"]:hover, .sidebar-item:hover,
                    [class*="hover:text-primary"]:hover, [class*="hover:text-purple"]:hover, [class*="hover:text-indigo"]:hover,
                    [class*="hover:bg-primary"]:hover, [class*="hover:bg-purple"]:hover, [class*="hover:bg-indigo"]:hover {
                        color: #476b32 !important;
                        background-color: #e6f3df !important;
                    }

                    /* --- 3. CAJAS DE TEXTO Y FORMULARIOS --- */
                    input:focus, select:focus, textarea:focus, button:focus,
                    [class*="focus:border-"], [class*="focus:ring-"], [class*="focus-within:ring-"] {
                        border-color: #72a651 !important;
                        --tw-ring-color: #72a651 !important;
                        --tw-ring-opacity: 0.3 !important;
                        box-shadow: 0 0 0 3px rgba(114, 166, 81, 0.35) !important;
                    }
                    
                    [class*="border-primary-"], [class*="border-purple-"], [class*="border-indigo-"],
                    .border-primary-600, .border-purple-600, .border-indigo-600 {
                        border-color: #72a651 !important;
                    }
                    
                    input[type="checkbox"]:checked {
                        background-color: #72a651 !important;
                        border-color: #5b893f !important;
                    }
                `;
                
                var style = document.createElement("style");
                style.type = "text/css";
                style.innerHTML = css;
                document.head.appendChild(style);
            })();
        </script>
        """
    ],
}